baseurl: /
pygments: true
title: Geekx
name: Geekx
description: Yet Another
url: https://vess.xyz
paginate: 5
disqus_shortname: hxbdx
paginate_path: "page:num"
markdown: redcarpet
style_version: 20150822

redcarpet:
 extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
